{
  default: kbcs,
  tb_meta: 
    {commands:
      [
        {
          command: quit, aliases: [q], description: "Close this application."
        },
        {
          command: next, aliases: [n], description: "Display metadata of next album."
        },
        {
          command: previous, aliases: [prev, p], description: "Display metadata of previous album."
        },
        {
          command: edit, aliases: [e], description: "Edit all metadata categories with the Metadata Input Friend."
        },
        {
          command: search, aliases: [s], description: "Search for MusicBrainz release in browser.",
          options: [
            {command: "<artist_name>", description: "Search for artist using specified name instead of name in metadata."},
            {command: "bar", description: "Search for release by barcode / catalog number."}
          ]
        },
        {
          command: bar, options: [command: "<barcode or catno>"], 
          description: "Search by barcode/catno. If no barcode or catalog number is entered, will search for barcode / catalog number in metadata."
        },
        {
          command: albunack, aliases: [al], description: "Search for release in Albunack in browser.",
          options: [
            {command: "<artist_name>", description: "Search for artist using specified name instead of name in metadata."},
            {command: "bar", description: "Search for release by barcode / catalog number."}
          ]
        }        
      ]
    },
  audiofile: !!python/name:audio_pipeline.util.AudioFile.BaseAudioFile '',
  batch constants: !!python/name:audio_pipeline.util.Resources.BatchConstants '',
  serializer: !!python/name:audio_pipeline.serializers.DaletSerializer.DaletSerializer '',
  custom_tags: {category: CATEGORY, item_code: ITEMCODE, obscenity: OBSCENITYRATING}
}