{default: kexp, audiofile: !!python/name:audio_pipeline.util.Resources.BatchConstants '',
processor: !!python/name:audio_pipeline.file_walker.Process.Processor '', 
serializer: !!python/name:audio_pipeline.serializers.DaletSerializer.DaletSerializer ''}